letters :: "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j" | "k" | "l" | "m" | "n" | "o" | "p" | "q" | "r" | "s" | "t" | "u" | "v" | "w" | "x" | "y" | "z"

vowels :: "a" | "e" | "i" | "o" | "u" | "y"
cons :: "b" | "c" | "d" | "f" | "g" | "h" | "j" | "k" | "l" | "m" | "n" | "p" | "q" | "r" | "s" | "t" | "v" | "w" | "x" | "z" 

digit :: (generate @nonzero)^9 | "0"
nonzero :: "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"